### PR TITLE
feat: Improve animations

### PR DESCRIPTION
**Pull request by bprusinowski**
This PR introduces further improvements to animations and some smaller improvements.

- Scatterplot and Pie now animate data updates
- Empty color legend is not shown anymore
- Map Chart now retains animation field when switching from a chart type that used this field
- TimeFilter now explicitly displays `from` and `to` fields
- TimeFilter brush now snaps to values from the data

### CODE REVIEW

**Comment by Rdataflow** [comment]
@bprusinowski thanks for sharing 👍 
repro link: https://visualization-tool-k4b8iwgez-ixt1.vercel.app/v/ba2figIOM4ev?dataSource=Prod
a first quick feedback: if enabling interactive time filter is enabled at the same time as animation
- the user gets an odd choice (1st and 2nd: 2014, 2015 - but not the later years)
- if chosen i.e. 2014 then, the animation is constrained to that selected year in consequence. so it's rather add to have this selection interactive then.

**Comment by bprusinowski** [comment]
Hi @Rdataflow, thanks for taking a look 🙇 Yes, this definitely shouldn't happen, I'll look into that 👍

**Comment by bprusinowski** [comment]
@Rdataflow I fixed this in https://github.com/visualize-admin/visualization-tool/pull/1103 👀

**Comment by ptbrowne** [comment]
LGTM, really good work 💯 Why testing the transitions I noticed that above the year filter I had "[Object object]". I tested starting from this link https://visualization-tool-k4b8iwgez-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd000504/6 then scatterplot then adding the Year filter.

**Comment by bprusinowski** [comment]
Thanks for reviewing, @ptbrowne! I fixed the issue in https://github.com/visualize-admin/visualization-tool/pull/1103/commits/e1e968eb8b9080292fed2fc9d0713d2149d5eb14

**Pull request merged**
