### PR TITLE
feat: removed beta tag

### LINKED ISSUE #1884: Improve Visibility of Selected Data Set: Remove Beta Label
Remove the Beta Label on the datasets section in the sidebar. 

Pending approval of #1800 

Image

### PR DESCRIPTION
**Pull request by noahonyejese**
**This PR:**
- This PR Removes the Beta Tag from the Datasets section 
- This PR resolves #1884 

### How to test 
1. Go to this [Link](https://vercel.live/open-feedback/visualization-tool-git-feat-remove-beta-tag-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 
2. Select a Dataset for a visualization 
3. See how the beta Tag from the Datasets Section is removed

---

CC: @sosiology , @KerstinFaye

### CODE REVIEW

**Review by bprusinowski — APPROVED** [review]
Thanks @noahonyejese 👍 

I think it could be cool to add a mention in the `CHANGELOG` that the merging of cubes beta tag was removed :)

Also I wonder if we shouldn't remove the beta tag from add dataset dialog? I know that the task was only mentioning this one place, but we also have the same tag related to merging of cubes there, might be worth to clarify with @sosiology.

**Comment by noahonyejese** [comment]
@bprusinowski makes total sense, I will add it to the `CHANGELOG` for now and wait for the confirmation by @sosiology

**Comment by sosiology** [comment]
@noahonyejese removal of the beta tag LGTM on the PR. Thanks.

**Comment by noahonyejese** [comment]
> @noahonyejese removal of the beta tag LGTM on the PR. Thanks.

should we me removing it, where @bprusinowski mentioned it as well?

**Comment by sosiology** [comment]
@noahonyejese thanks for your question, sorry i missed it - lets discuss in our sync this morning

**Pull request merged**
