### PR TITLE
perf: Optimize initializing chart from cube

### LINKED ISSUE #1658: possible filter and components query needlessly fires twice - and takes a very long time
**To Do**

- [ ] exclude non-key dimensions from the most expensive query fired when initializing a chart from cube 

@bprusinowski very similar results are fetched twice - most of which aren't even needed (non-key) - thanks for taking a look

**Describe the bug**
The rework of https://github.com/visualize-admin/visualization-tool/pull/1487 shows a tiny glitch endin up in a big difference on milk cubes.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://int.visualize.admin.ch/browse?dataset=https%3A%2F%2Fagriculture.ld.admin.ch%2Ffoag%2Fcube%2FMilkDairyProducts%2FConsumption_Price_Month&dataSource=Int-uncached
2. Enable Debug mode
3. Create visualization
4. See queryplan and GraphQL waterfall

**Expected behavior**
- possible filters are fetched once
- overall cubeComponents are fetched once using a speedy query

**Actual behavior**
- possible filters are fetched twice
- overall cubeComponents are fetched twice, the second query is very slow (and asks for information about every single non-keyDimension which becomes expensive and takes > 20s)
- OTOH the chart already appears perfectly a few seconds from the start
- so it's just the left panel (and not the filters) which fires that expensive re-query

**Screenshots or video**
image

**Environment (please complete the following information):**
- Visualize environment and version: INT 4.7.2

**Additional context**
the query needlessly re-asking for information over **all** dimensions
[get.components.expensive.txt](https://github.com/user-attachments/files/16138972/get.components.expensive.txt)
```
curl 'https://int.visualize.admin.ch/api/graphql' -X POST -H 'content-type: application/json' --data-raw '{"operationName":"DataCubeComponents","variables":{"locale":"de","sourceType":"sparql","sourceUrl":"https://lindas.admin.ch/query","cubeFilter":{"iri":"https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Consumption_Price_Month","filters":{"https://agriculture.ld.admin.ch/foag/dimension/product":{"type":"single","value":"https://agriculture.ld.admin.ch/foag/product/193"},"https://agriculture.ld.admin.ch/foag/dimension/value-chain-detail":{"type":"single","value":"https://agriculture.ld.admin.ch/foag/value-chain-detail/18"},"https://agriculture.ld.admin.ch/foag/dimension/key-indicator-type":{"type":"single","value":"https://agriculture.ld.admin.ch/foag/key-indicator-type/1"},"https://agriculture.ld.admin.ch/foag/dimension/production-system":{"type":"single","value":"https://agriculture.ld.admin.ch/foag/production-system/3"}},"loadValues":true}},"query":"query DataCubeComponents($sourceType: String!, $sourceUrl: String!, $locale: String!, $cubeFilter: DataCubeComponentFilter!) {\n  dataCubeComponents(\n    sourceType: $sourceType\n    sourceUrl: $sourceUrl\n    locale: $locale\n    cubeFilter: $cubeFilter\n  )\n}\n"}'
```
```sparql
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/cost-component> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/currency> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/data-method> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/data-source> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/date> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/foreign-trade> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/key-indicator-type> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/market> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/product> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/product-group> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/production-system> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/product-origin> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/product-properties> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/product-subgroup> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/sales-region> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/unit> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/usage> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/value-chain> } 
VALUES ?dimensionIri { <https://agriculture.ld.admin.ch/foag/dimension/value-chain-detail> }
```

### PR DESCRIPTION
**Pull request by bprusinowski**
Potentially closes #1658

This PR removes fetching of all dimensions with values in favor of re-using a cube preview query when initializing a chart from cube. I am not 100% convinced it improves the performance in a visible way, but at least we removed a potentially expensive query in favor of the preview one, that only fetches one dimension value for every dimension.

### CODE REVIEW

**Review by noahonyejese — APPROVED** [review]
LGTM  ✔️, Even if it doesn't perform much better visually, the query was pretty expensive...

**Comment by bprusinowski** [comment]
Ah, good catch @noahonyejese :) I forgot to mock the response for `DataCubePreview` query in tests, so some of them fail 🤦‍♂️ I will fix them, however no code was modified in `DataCubeObservations` query, I assume this check failed due to LINDAS being unstable, which happens quite frequently 😅

**Comment by noahonyejese** [comment]
> Ah, good catch @noahonyejese :) I forgot to mock the response for `DataCubePreview` query in tests, so some of them fail 🤦‍♂️ I will fix them, however no code was modified in `DataCubeObservations` query, I assume this check failed due to LINDAS being unstable, which happens quite frequently 😅

Yeah I've noticed that LINDAS is quite unstable sometimes....

**Comment by bprusinowski** [comment]
Closing in favor of https://github.com/visualize-admin/visualization-tool/pull/1890

**Pull request closed without merging**
