### PR TITLE
chore: Update cube-hierarchy query library

### PR DESCRIPTION
**Pull request by bprusinowski**
This PR:
- updates `cube-hierarchy-query` library from 2.0.0 to 2.2.2,
- fetches hierarchies only when values are needed (`loadValues: true`).

### CODE REVIEW

**Comment by Rdataflow** [comment]
@bprusinowski please consider adding the `properties` parameter as in https://github.com/visualize-admin/visualization-tool/pull/1223/files#diff-d1b5627a8f8371b03dc51e502a73c2bbc4f348b4dfc87458d0cf95dbdb41939fR156-R162

i.e. 
```
          properties: [
            ns.schema.identifier,
            ns.schema.name,
            ns.schema.description,
            ns.schema.position,
            ns.schema.alternateName,
          ],
```

NB: I suggest to add the properties without `language` filter in this first step... that may be added later on for name and description...

finally: observe improved performance at https://test.visualize.admin.ch/create/new?cube=https://culture.ld.admin.ch/sfa/nettoreach_tv_broadcaster/23&dataSource=Int

**Comment by bprusinowski** [comment]
@Rdataflow unfortunately there appear to be some issues with specifying properties to fetch along with hierarchies that are hard to debug.

When adding

```ts
properties: [
  ns.schema.identifier,
  ns.schema.name,
  ns.schema.description,
  ns.schema.position,
  ns.schema.alternateName,
],
```

as proposed, function fetches correct values for [Bathing water quality](https://test.visualize.admin.ch/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd0104/12&dataSource=Int) (Observation location), but breaks the hierarchies for [NFI cube](https://test.visualize.admin.ch/en/create/new?cube=https://environment.ld.admin.ch/foen/nfi/nfi_C-20/cube/2023-3&dataSource=Prod) (Region).

However when using

```ts
properties: [
  ns.schema.identifier,
  [ns.schema.name, { language: locale }],
  ns.schema.description,
  ns.schema.position,
  ns.schema.alternateName,
],
```

the situation reverses and now Bathing water quality is broken, but NFI cube works.

I would propose to merge this PR as it already should bring some performance improvements and investigate the issue with specifying properties in another PR 👀

**Comment by Rdataflow** [comment]
@bprusinowski FYI: Marco told me the NFI hierarchies were broken this morning. The are fixed now. Can you retry if the issue for NFI Regions still persists?

**Comment by Rdataflow** [comment]
@bprusinowski v2.2.2 is way faster now :rocket: 
:heart: https://github.com/visualize-admin/visualization-tool/pull/1364/commits/3efd95390edb2c341a522c8a330280c0c792d8cd

**Pull request merged**
