### PR TITLE
perf: Switch to a cached LINDAS endpoint (PROD)

### LINKED ISSUE #1369: Switch to a cached LINDAS endpoint
**Description**
Currently, we use non-cached data API endpoints on every data environment (TEST, INT, PROD).

For PROD there has been deplodey a cached versions of the PROD endpoint, we would like to switch to that in order to potentially increase the feeling of application being performant. This cached PROD endpoint has been applied and tested for the https://strompreis.elcom.admin.ch/ already.

**User story**

I would like the application to react faster when doing the same actions (which should result in hitting cache directly on LINDAS side).

**Definition of Done**

Visualize uses the cached endpoint [1] for LINDAS PROD instead of non-cached endpoint.

[1] https://lindas-cached.cluster.ldbar.ch/query

### PR DESCRIPTION
**Pull request by bprusinowski**
Closes #1369

### CODE REVIEW

**Comment by Rdataflow** [comment]
@bprusinowski for some odd reason this endpoint breaks ...  I'll keep you updated on how to proceed

**Comment by bprusinowski** [comment]
@Rdataflow yup, we won't merge this now – thanks for asking Zazuko, let's see what happens there 👍

**Comment by Rdataflow** [comment]
FTR: with the new version of trifid on PROD the cached endpoint works like a charm now - we keep monitoring the situation 👀

**Comment by bprusinowski** [comment]
@Rdataflow the preview is being re-deployed with latest changes from `main`, should be up in ~5 mins.

**Review by ptbrowne — APPROVED** [review]

**Comment by Rdataflow** [comment]
@claudiodigallo just give your green light directly to ITX once the situation on your side is ready 👍 

cc @sosiology

**Comment by sosiology** [comment]
@CDiGallo thanks for the green light! In that case, we can merge this PR after the release tomorrow, is that okay or is the expectation that this is part of the Release to PROD?

Cc: @Rdataflow @bprusinowski

**Comment by CDiGallo** [comment]
No, this is only for visualize test

**Comment by sosiology** [comment]
@CDiGallo perfect! We will merge to test.

**Pull request merged**
