### PR TITLE
Status page links

### PR DESCRIPTION
**Pull request by ptbrowne**
- feat: Add footer to search results page
- feat: Add mention of page status in data loading error hint

### CODE REVIEW

**Review by bprusinowski — APPROVED** [review]
👌

**Comment by ptbrowne** [comment]
Waiting until client approval.

**Comment by Rdataflow** [comment]
LGTM 👍

**Comment by sosiology** [comment]
- [ ] Remove logo
- [ ] Add LD Platform Status Page link (at the bottom) https://status.ldbar.ch/
- [ ] Implement banner / error message with link to status page

**Pull request merged**
