### PR TITLE
feat: Activate shared filters for "tab" layout

### PR DESCRIPTION
**Pull request by ptbrowne**
Activate dashboard filters for tab layout

- [x] In configurator mode
- [x] In published mode

### CODE REVIEW

**Review by bprusinowski — COMMENTED** [review]
Code looks good, but I think the state of the filters should be persisted when switching through the charts in the tab layout, otherwise the "shared" part doesn't really apply 😅 I can also take a look in the coming days, let me know 👍

**Comment by bprusinowski** [comment]
Ah, I see that it's in fact persisted, it's just the slider that's initialized with the full range on switch 🤔

**Comment by bprusinowski** [comment]
On a side note: I wonder if we shouldn't disable enter animations for charts, currently it's quite bad for a column chart (falls down from the top). This would also make it easier to compare the changes when switching thought the tabs, what do you think?

**Comment by ptbrowne** [comment]
I'll take a look, thanks.

**Review by bprusinowski — APPROVED** [review]
🎉

**Pull request merged**
