### PR TITLE
chore: Update hierarchy query library

### PR DESCRIPTION
**Pull request by bprusinowski**
This PR updates the cube-hierarchy-query library to v2.2.0.

It also updates the way of how we fetch dimension values metadata for hierarchies by using new syntax to directly specify the properties we need to fetch along the hierarchy. However, this seem to make it significantly less performant that our current approach, which means we should probably only update library, but keep the old way of fetching things.

**New auto-generated query used to fetch hierarchies and metadata ([NFI dataset](https://test.visualize.admin.ch/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-90%2Fcube%2F2023-2&dataSource=Prod)) – approx. 15s**
```
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT { 
  ?resource1 schema:identifier ?resource2 .
  ?resource1 schema:name ?resource3 .
  ?resource1 schema:description ?resource5 .
  ?resource1 schema:position ?resource7 .
  ?resource1 schema:alternateName ?resource8 .
  ?resource1 rdf:type ?resource10 .
  ?resource11 schema:containedInPlace ?resource1 .
  ?resource11 schema:identifier ?resource12 .
  ?resource11 schema:name ?resource13 .
  ?resource11 schema:description ?resource15 .
  ?resource11 schema:position ?resource17 .
  ?resource11 schema:alternateName ?resource18 .
  ?resource11 rdf:type ?resource20 .
}
WHERE {
  VALUES ( ?resource1 ) {
    ( <https://ld.admin.ch/country/CHE> )
  }
  {   
    ?resource1 schema:identifier ?resource2 .
  } UNION {
  {
    VALUES ( ?resource1 ) {
     ( <https://ld.admin.ch/country/CHE> )
    }
    ?resource1 schema:name ?resource3 .
    FILTER (lang(?resource3) = "de" ) }
  } UNION {    
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

      ?resource1 schema:description ?resource5 .
      FILTER (lang(?resource5) = "de" ) }

    } UNION {
      
?resource1 schema:position ?resource7 .

    } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

      ?resource1 schema:alternateName ?resource8 .
      FILTER (lang(?resource8) = "de" ) }

    } UNION {
      
?resource1 rdf:type ?resource10 .

    } UNION {
      { 
    
?resource11 schema:containedInPlace ?resource1 .
 
  } UNION {
      
            
?resource11 schema:containedInPlace ?resource1 .

            

{ 
    
?resource11 schema:identifier ?resource12 .
 
  } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

?resource11 schema:containedInPlace ?resource1 .



      ?resource11 schema:name ?resource13 .
      FILTER (lang(?resource13) = "de" ) }

    } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

?resource11 schema:containedInPlace ?resource1 .



      ?resource11 schema:description ?resource15 .
      FILTER (lang(?resource15) = "de" ) }

    } UNION {
      
?resource11 schema:position ?resource17 .

    } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

?resource11 schema:containedInPlace ?resource1 .



      ?resource11 schema:alternateName ?resource18 .
      FILTER (lang(?resource18) = "de" ) }

    } UNION {
      
?resource11 rdf:type ?resource20 .

    }

          
    }
    }


      ?resource1 ^schema:containedInPlace ?resource11 .
      ?resource11 a <https://environment.ld.admin.ch/foen/nfi/UnitOfReference/827> .
    
  
}
```

**Old auto-generated query to fetch hierarchies (([NFI dataset](https://test.visualize.admin.ch/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-90%2Fcube%2F2023-2&dataSource=Prod)) ) – approx. 2s**
```
PREFIX schema: <http://schema.org/>

CONSTRUCT { 
    ?resource2 schema:containedInPlace ?resource1 .
?resource2 ?resource3 ?resource4 .
?resource1 ?resource5 ?resource6 .
   }

WHERE {

    

VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}
{ 
    { 
    
?resource2 schema:containedInPlace ?resource1 .
 
  } UNION {
      
            
?resource2 schema:containedInPlace ?resource1 .

            


        ?resource2 ?resource3 ?resource4 .
        
        
      

          
    } 
  } UNION {
      
        ?resource1 ?resource5 ?resource6 .
        
        
      
    }


      ?resource1 ^schema:containedInPlace ?resource2 .
      ?resource2 a <https://environment.ld.admin.ch/foen/nfi/UnitOfReference/827> .
    
  
}
```

### CODE REVIEW

**Comment by Rdataflow** [comment]
@bprusinowski unfortunately https://visualization-tool-am4klf8am-ixt1.vercel.app/create/new?cube=https://environment.ld.admin.ch/foen/nfi/nfi_C-90/cube/2023-2&dataSource=Prod fails to load with this changes... there might be something important missing yet

**Comment by Rdataflow** [comment]
@bprusinowski hmm this would be the contrary of the performance improvements to strive for...
maybe adrian has input on this generated query?
wanna retry and omit the lang filters?

nb: @bprusinowski don't merge this PR yet... I'll tell you more

**Comment by Rdataflow** [comment]
@bprusinowski good to know, can you share your slow experience and the probable reason here to keep awareness:
https://gitlab.ldbar.ch/bafu/visualize/-/issues/548
THX

**Comment by t0b3** [comment]
@bprusinowski can you rebase this PR to current main?

**Comment by Rdataflow** [comment]
@bprusinowski can you rebase this PR to main?

**Comment by bprusinowski** [comment]
Hey @Rdataflow, the base is actually main. Did you mean to merge it to main?

**Comment by Rdataflow** [comment]
> Hey @Rdataflow, the base is actually main. Did you mean to merge it to main?

I just would like to see the latest commits from main branch included for the preview, thus only rebase on main trunk...

**Comment by bprusinowski** [comment]
Ah I see, done 👍

**Comment by Rdataflow** [comment]
@bprusinowski v2.1.1 is out now :rocket: let's give it a try

**Comment by bprusinowski** [comment]
@Rdataflow it looks that the performance is still not ideal when using language filters; when removed, it gets much better. Let me know if we should simply switch to querying all languages and extracting them on our own 👀 

Generated query (not visible in deployment preview due to >15s execution time)
```
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT { 
    ?resource1 schema:identifier ?resource2 .
?resource1 schema:name ?resource3 .
?resource1 schema:description ?resource5 .
?resource1 schema:position ?resource7 .
?resource1 schema:alternateName ?resource8 .
?resource1 rdf:type ?resource10 .
?resource11 schema:containedInPlace ?resource1 .
?resource11 schema:identifier ?resource12 .
?resource11 schema:name ?resource13 .
?resource11 schema:description ?resource15 .
?resource11 schema:position ?resource17 .
?resource11 schema:alternateName ?resource18 .
?resource11 rdf:type ?resource20 .
   }

WHERE {

    

VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}
{ 
    
?resource1 schema:identifier ?resource2 .
 
  } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

      ?resource1 schema:name ?resource3 .
      FILTER (lang(?resource3) = "en" ) }

    } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

      ?resource1 schema:description ?resource5 .
      FILTER (lang(?resource5) = "en" ) }

    } UNION {
      
?resource1 schema:position ?resource7 .

    } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

      ?resource1 schema:alternateName ?resource8 .
      FILTER (lang(?resource8) = "en" ) }

    } UNION {
      
?resource1 rdf:type ?resource10 .

    } UNION {
      { 
    
?resource11 schema:containedInPlace ?resource1 .
 
  } UNION {
      
            
?resource11 schema:containedInPlace ?resource1 .

            

{ 
    
?resource11 schema:identifier ?resource12 .
 
  } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

?resource11 schema:containedInPlace ?resource1 .



      ?resource11 schema:name ?resource13 .
      FILTER (lang(?resource13) = "en" ) }

    } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

?resource11 schema:containedInPlace ?resource1 .



      ?resource11 schema:description ?resource15 .
      FILTER (lang(?resource15) = "en" ) }

    } UNION {
      
?resource11 schema:position ?resource17 .

    } UNION {
      
{ 
VALUES ( ?resource1 )
{
( <https://ld.admin.ch/country/CHE> )
}

?resource11 schema:containedInPlace ?resource1 .



      ?resource11 schema:alternateName ?resource18 .
      FILTER (lang(?resource18) = "en" ) }

    } UNION {
      
?resource11 rdf:type ?resource20 .

    }

          
    }
    }


      ?resource1 ^schema:containedInPlace ?resource11 .
      ?resource11 a <https://environment.ld.admin.ch/foen/nfi/UnitOfReference/49> .
    
  
}
```

**Comment by bprusinowski** [comment]
Closed in favor of #1364.

**Pull request closed without merging**
