### PR TITLE
Column order for table

### PR DESCRIPTION
**Pull request by ptbrowne**
- refactor: Separate fixtures between data and configs
- feat: Initial config for table uses dimension "order" property

Fixes https://github.com/visualize-admin/visualization-tool/issues/78

### CODE REVIEW

**Review by bprusinowski — APPROVED** [review]
👌

**Comment by ptbrowne** [comment]
I merged since the test is failing because of the hierarchy having disappeared on @FabianCretton's cube.

**Comment by FabianCretton** [comment]
@ptbrowne I do not know about this conversation, but you talk about one of my cube where the hierarchy has disappeared, can you tell me what it is ? Thanks

**Comment by ptbrowne** [comment]
Hi Fabian 👋  I used the Zulip of Zazuko to contact you : https://zulip.zazuko.com/#narrow/stream/40-bafu-ext/topic/Hierarchie.20removed.20from.20cube , tell me if there is a better way ;)

**Comment by FabianCretton** [comment]
it is perfect there @ptbrowne, I didn't see yet my notifications about this, sorry

**Pull request merged**
