### PR TITLE
docs: Add cube update rules

### PR DESCRIPTION
**Pull request by ptbrowne**
Add documentation on how to safely update a cube so that charts still work.

### CODE REVIEW

**Review by herrstucki — APPROVED** [review]

**Comment by l00mi** [comment]
Noooo, I was writing a review ((-..

Minor thing, can we remove the elipsis .. and just state what can not change of the structure. Its these three things, datatype, datakind, scale of measure and dimension type. What about Unit?

**Comment by ptbrowne** [comment]
Thanks good idea to remove the ellipsis and be explicit. I went through the cube schema doc to list the properties.

**Comment by l00mi** [comment]
Thank you, very good. It add a suprise for me, why would the `sh:order` invalidate an update?

**Comment by ptbrowne** [comment]
I added it as a precaution. I struggled a bit to find an example but for example for maps, the order could be used for the z-order of layers and changing the order could make one shape go below another one. It might be over-zealous I concede. We could re add it if necessary.

**Comment by l00mi** [comment]
> I added it as a precaution. I struggled a bit to find an example but for example for maps, the order could be used for the z-order of layers and changing the order could make one shape go below another one. It might be over-zealous I concede. We could re add it if necessary.

No example yet, we need to implement it still in the cube-creator. The cubes from WSL, not created by Cube-Creator might already provide it.

**Pull request merged**
