### PR TITLE
feat: Improve chart sizes preview

### PR DESCRIPTION
**Pull request by bprusinowski**
This PR:
- fixes https://github.com/visualize-admin/visualization-tool/pull/1724#issuecomment-2334360578 by using container queries,
- adjusts width of smallest preview breakpoint from `sm` (768px) to 480px,
- fixes an overflowing issue with previewing / resizing the window in the Tall layout.

### CODE REVIEW

**Review by noahonyejese — APPROVED** [review]
Nice fixes and improvements 👍🏽

**Comment by bprusinowski** [comment]
Thanks @noahonyejese 🙇‍♂️ Still trying to figure our why CSS module is not properly mocked 😅

**Comment by noahonyejese** [comment]
I’ll check once I’m in the train 👍🏽

**Comment by bprusinowski** [comment]
It looks like the "@" rule was being applied first, which resulted to importing CSS files and some issues; I fixed this by reversing the order https://github.com/visualize-admin/visualization-tool/pull/1733/commits/b29f750ddb346c051d3f7104bd895a6301cc1d94 👍

**Pull request merged**
